site_name: Obtainium Wiki
repo_url: https://github.com/ImranR98/Obtainium
site_description: Help page for Obtainium
docs_dir: pages
site_author: ImranR98
edit_uri: https://github.com/ImranR98/Obtainium-Wiki/edit/main/pages/

nav:
  - Home: index.md
  - UI Overview: ui_overview.md
  - How Apps are Tracked: app_tracking.md
  - App Sources: sources.md
  - Settings: settings.md

theme:
  name: material
  logo: assets/logo.png
  custom_dir: pages/overrides
  favicon: https://raw.githubusercontent.com/ImranR98/Obtainium/main/assets/graphics/icon_small.png

  features:
    - content.action.edit
    - search.suggest
    - search.highlight
    - navigation.top

  icon:
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle

  palette:
    - primary: deep purple

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: simple/github
      link: https://github.com/ImranR98/
      name: GitHub
    - icon: simple/mastodon
      link: https://freeradical.zone/@imran
      name: Mastodon
    - icon: simple/kofi
      link: https://ko-fi.com/imranr
      name: Ko-fi
    - icon: material/heart
      link: https://github.com/sponsors/ImranR98
      name: GitHub Sponsors
    - icon: material/web
      link: https://imranr.dev/
      name: Website
  
  translations:
    en:
      made_by: Made By
      open_an_issue: Open an Issue
      crowdsourced_app_configs: Crowdsourced App Configurations
      obtainium_website: Obtainium Website
      made_with: Made with

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: 🇬🇧 English

        - locale: de
          name: 🇩🇪 Deutsch
          site_name: "Obtainium Wiki"
          site_description: "Hilfeseite für Obtainium"
          nav_translations:
            UI Overview: Übersicht User Interface
            How Apps are Tracked: Wie Apps nachverfolgt werden

        - locale: "null"
          name: ➕ Add
          build: false
          fixed_link: https://github.com/ImranR98/Obtainium-Wiki/blob/main/CONTRIBUTING.md

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - assets/analytics.js
